
#line 3 "lex.RegYY.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define RegYYconst const
#else
#define RegYYconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (RegYY_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((RegYY_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE RegYYrestart(RegYYin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(RegYY_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct RegYY_buffer_state *YY_BUFFER_STATE;
#endif

extern int RegYYleng;

extern FILE *RegYYin, *RegYYout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define RegYYless(n) \
	do \
		{ \
		/* Undo effects of setting up RegYYtext. */ \
        int RegYYless_macro_arg = (n); \
        YY_LESS_LINENO(RegYYless_macro_arg);\
		*RegYY_cp = (RegYY_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(RegYY_c_buf_p) = RegYY_cp = RegYY_bp + RegYYless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up RegYYtext again */ \
		} \
	while ( 0 )

#define unput(c) RegYYunput( c, (RegYYtext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t RegYY_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct RegYY_buffer_state
	{
	FILE *RegYY_input_file;

	char *RegYY_ch_buf;		/* input buffer */
	char *RegYY_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	RegYY_size_t RegYY_buf_size;

	/* Number of characters read into RegYY_ch_buf, not including EOB
	 * characters.
	 */
	int RegYY_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int RegYY_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int RegYY_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int RegYY_at_bol;

    int RegYY_bs_lineno; /**< The line count. */
    int RegYY_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int RegYY_fill_buffer;

	int RegYY_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via RegYYrestart()), so that the user can continue scanning by
	 * just pointing RegYYin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t RegYY_buffer_stack_top = 0; /**< index of top of stack. */
static size_t RegYY_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * RegYY_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (RegYY_buffer_stack) \
                          ? (RegYY_buffer_stack)[(RegYY_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (RegYY_buffer_stack)[(RegYY_buffer_stack_top)]

/* RegYY_hold_char holds the character lost when RegYYtext is formed. */
static char RegYY_hold_char;
static int RegYY_n_chars;		/* number of characters read into RegYY_ch_buf */
int RegYYleng;

/* Points to current character in buffer. */
static char *RegYY_c_buf_p = (char *) 0;
static int RegYY_init = 0;		/* whether we need to initialize */
static int RegYY_start = 0;	/* start state number */

/* Flag which is used to allow RegYYwrap()'s to do buffer switches
 * instead of setting up a fresh RegYYin.  A bit of a hack ...
 */
static int RegYY_did_buffer_switch_on_eof;

void RegYYrestart (FILE *input_file  );
void RegYY_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE RegYY_create_buffer (FILE *file,int size  );
void RegYY_delete_buffer (YY_BUFFER_STATE b  );
void RegYY_flush_buffer (YY_BUFFER_STATE b  );
void RegYYpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void RegYYpop_buffer_state (void );

static void RegYYensure_buffer_stack (void );
static void RegYY_load_buffer_state (void );
static void RegYY_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER RegYY_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE RegYY_scan_buffer (char *base,RegYY_size_t size  );
YY_BUFFER_STATE RegYY_scan_string (RegYYconst char *RegYY_str  );
YY_BUFFER_STATE RegYY_scan_bytes (RegYYconst char *bytes,int len  );

void *RegYYalloc (RegYY_size_t  );
void *RegYYrealloc (void *,RegYY_size_t  );
void RegYYfree (void *  );

#define RegYY_new_buffer RegYY_create_buffer

#define RegYY_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        RegYYensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            RegYY_create_buffer(RegYYin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->RegYY_is_interactive = is_interactive; \
	}

#define RegYY_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        RegYYensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            RegYY_create_buffer(RegYYin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->RegYY_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->RegYY_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *RegYYin = (FILE *) 0, *RegYYout = (FILE *) 0;

typedef int RegYY_state_type;

extern int RegYYlineno;

int RegYYlineno = 1;

extern char *RegYYtext;
#define RegYYtext_ptr RegYYtext

static RegYY_state_type RegYY_get_previous_state (void );
static RegYY_state_type RegYY_try_NUL_trans (RegYY_state_type current_state  );
static int RegYY_get_next_buffer (void );
static void RegYY_fatal_error (RegYYconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up RegYYtext.
 */
#define YY_DO_BEFORE_ACTION \
	(RegYYtext_ptr) = RegYY_bp; \
	RegYYleng = (size_t) (RegYY_cp - RegYY_bp); \
	(RegYY_hold_char) = *RegYY_cp; \
	*RegYY_cp = '\0'; \
	(RegYY_c_buf_p) = RegYY_cp;

#define YY_NUM_RULES 27
#define YY_END_OF_BUFFER 28
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct RegYY_trans_info
	{
	flex_int32_t RegYY_verify;
	flex_int32_t RegYY_nxt;
	};
static RegYYconst flex_int16_t RegYY_accept[46] =
    {   0,
        0,    0,    0,    0,    0,    0,   28,   27,   26,   22,
       25,   13,   14,   10,   12,   23,   11,   16,   26,   24,
       21,   20,   27,   20,   20,   17,   15,    6,    7,    8,
        2,    1,    3,    4,    5,    0,    0,   19,    0,   18,
        0,    0,    0,    9,    0
    } ;

static RegYYconst flex_int32_t RegYY_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    1,    1,    1,    4,
        5,    6,    7,    8,    9,   10,    1,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    1,    1,    1,
        1,    1,   12,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       13,   14,   15,   16,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   17,    1,    1,    1,    1,
        1,    1,   18,   19,   20,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static RegYYconst flex_int32_t RegYY_meta[21] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    1,
        1,    1,    1,    1,    2,    1,    1,    1,    1,    1
    } ;

static RegYYconst flex_int16_t RegYY_base[49] =
    {   0,
        0,    0,    0,    0,   19,   33,   43,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   25,   46,   69,
       69,   31,   29,   69,   13,   28,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   21,    0,   69,   15,   69,
       13,   11,   25,   69,   69,   64,   66,   24
    } ;

static RegYYconst flex_int16_t RegYY_def[49] =
    {   0,
       46,   46,   45,    3,   47,   47,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   48,   45,   45,   45,
       45,   45,   45,   45,    0,   45,   45,   45
    } ;

static RegYYconst flex_int16_t RegYY_nxt[90] =
    {   0,
        9,   10,   11,   12,   13,   14,   15,    9,    9,   16,
        9,   17,   18,   19,    9,   20,    9,    9,   21,    9,
       23,   37,   41,   43,   40,   39,   42,   24,   42,   38,
       44,   39,   25,   26,   23,   43,   37,   37,   42,   37,
       27,   24,   45,   45,   45,   45,   25,   26,   28,   29,
       30,   31,   45,   45,   45,   32,   45,   33,   45,   34,
       45,   35,   45,   36,    8,    8,   22,   22,    7,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45
    } ;

static RegYYconst flex_int16_t RegYY_chk[90] =
    {   0,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        5,   25,   39,   41,   48,   39,   41,    5,   39,   25,
       42,   36,    5,    5,    6,   43,   26,   23,   43,   22,
       18,    6,    7,    0,    0,    0,    6,    6,   19,   19,
       19,   19,    0,    0,    0,   19,    0,   19,    0,   19,
        0,   19,    0,   19,   46,   46,   47,   47,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45
    } ;

static RegYY_state_type RegYY_last_accepting_state;
static char *RegYY_last_accepting_cpos;

extern int RegYY_flex_debug;
int RegYY_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define RegYYmore() RegYYmore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *RegYYtext;
#line 1 "RegLex.l"
#line 2 "RegLex.l"
#include <stdio.h>
#include <stdlib.h>

#include <Reg.h>

#include <RegParse.h>

int RegLexInput ();

#ifndef YY_NO_INPUT

#undef input
#define input RegLexInput

#else

#undef YY_INPUT
#define YY_INPUT(buffer,result,max_size) \
{ \
  int c = '*', n; \
  for ( n = 0; n < max_size && \
               ((c = RegLexInput()) != 0) && \
               (c != '\n'); ++n ) \
    { \
      buffer[n] = (char) c; \
    } \
  if ( c == '\n' ) buffer[n++] = (char) c; \
  result = n; \
}

#endif

#undef unput
#define unput RegLexUnput
static void RegLexUnput (int c);

int RegYYwrap ();
int RegYYlook ();
int RegYYback ();

static int SetPosition = 0;
static int Level = 0;
static int* Positions = 0;
static int Position = 0;
static int Levels = 0;
static char* CurrentText = 0;
static int CurrentPos = 0;

void IncLevel ();
void DecLevel ();
void IncPosition ();
void ResetPosition ();



#line 543 "lex.RegYY.c"

#define INITIAL 0
#define EXP 1
#define SET 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int RegYY_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int RegYYlex_destroy (void );

int RegYYget_debug (void );

void RegYYset_debug (int debug_flag  );

YY_EXTRA_TYPE RegYYget_extra (void );

void RegYYset_extra (YY_EXTRA_TYPE user_defined  );

FILE *RegYYget_in (void );

void RegYYset_in  (FILE * in_str  );

FILE *RegYYget_out (void );

void RegYYset_out  (FILE * out_str  );

int RegYYget_leng (void );

char *RegYYget_text (void );

int RegYYget_lineno (void );

void RegYYset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int RegYYwrap (void );
#else
extern int RegYYwrap (void );
#endif
#endif

    static void RegYYunput (int c,char *buf_ptr  );
    
#ifndef RegYYtext_ptr
static void RegYY_flex_strncpy (char *,RegYYconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int RegYY_flex_strlen (RegYYconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int RegYYinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( RegYYtext, RegYYleng, 1, RegYYout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->RegYY_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( RegYYin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( RegYYin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, RegYYin))==0 && ferror(RegYYin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(RegYYin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "RegYYterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef RegYYterminate
#define RegYYterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) RegYY_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int RegYYlex (void);

#define YY_DECL int RegYYlex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after RegYYtext and RegYYleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register RegYY_state_type RegYY_current_state;
	register char *RegYY_cp, *RegYY_bp;
	register int RegYY_act;
    
#line 62 "RegLex.l"


#line 735 "lex.RegYY.c"

	if ( !(RegYY_init) )
		{
		(RegYY_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (RegYY_start) )
			(RegYY_start) = 1;	/* first start state */

		if ( ! RegYYin )
			RegYYin = stdin;

		if ( ! RegYYout )
			RegYYout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			RegYYensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				RegYY_create_buffer(RegYYin,YY_BUF_SIZE );
		}

		RegYY_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		RegYY_cp = (RegYY_c_buf_p);

		/* Support of RegYYtext. */
		*RegYY_cp = (RegYY_hold_char);

		/* RegYY_bp points to the position in RegYY_ch_buf of the start of
		 * the current run.
		 */
		RegYY_bp = RegYY_cp;

		RegYY_current_state = (RegYY_start);
RegYY_match:
		do
			{
			register YY_CHAR RegYY_c = RegYY_ec[YY_SC_TO_UI(*RegYY_cp)];
			if ( RegYY_accept[RegYY_current_state] )
				{
				(RegYY_last_accepting_state) = RegYY_current_state;
				(RegYY_last_accepting_cpos) = RegYY_cp;
				}
			while ( RegYY_chk[RegYY_base[RegYY_current_state] + RegYY_c] != RegYY_current_state )
				{
				RegYY_current_state = (int) RegYY_def[RegYY_current_state];
				if ( RegYY_current_state >= 46 )
					RegYY_c = RegYY_meta[(unsigned int) RegYY_c];
				}
			RegYY_current_state = RegYY_nxt[RegYY_base[RegYY_current_state] + (unsigned int) RegYY_c];
			++RegYY_cp;
			}
		while ( RegYY_base[RegYY_current_state] != 69 );

RegYY_find_action:
		RegYY_act = RegYY_accept[RegYY_current_state];
		if ( RegYY_act == 0 )
			{ /* have to back up */
			RegYY_cp = (RegYY_last_accepting_cpos);
			RegYY_current_state = (RegYY_last_accepting_state);
			RegYY_act = RegYY_accept[RegYY_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( RegYY_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*RegYY_cp = (RegYY_hold_char);
			RegYY_cp = (RegYY_last_accepting_cpos);
			RegYY_current_state = (RegYY_last_accepting_state);
			goto RegYY_find_action;

case 1:
YY_RULE_SETUP
#line 64 "RegLex.l"
{
  IncPosition ();
  RegYYlval.character = RegYYtext[1];
  return (CHARACTER);
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 70 "RegLex.l"
{
  IncPosition ();
  RegYYlval.character = RegYYtext[1];
  return (CHARACTER);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 76 "RegLex.l"
{
  IncPosition ();
  RegYYlval.character = RegYYtext[1];
  return (CHARACTER);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 82 "RegLex.l"
{
  IncPosition ();
  RegYYlval.character = RegYYtext[1];
  return (CHARACTER);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 88 "RegLex.l"
{
  IncPosition ();
  RegYYlval.character = RegYYtext[1];
  return (CHARACTER);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 94 "RegLex.l"
{
  IncPosition ();
  RegYYlval.character = RegYYtext[1];
  return (CHARACTER);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 100 "RegLex.l"
{
  IncPosition ();
  RegYYlval.character = RegYYtext[1];
  return (CHARACTER);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 106 "RegLex.l"
{
  IncPosition ();
  RegYYlval.character = RegYYtext[1];
  return (CHARACTER);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 112 "RegLex.l"
{
  static RegValueRangeRec range;

  IncPosition ();
  sscanf ((char*) &RegYYtext[2], "%d,%d", &range.val1, &range.val2);
  RegYYlval.valueRange = &range;
  return (VALUERANGE);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 121 "RegLex.l"
{
  return (STAR);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 125 "RegLex.l"
{
  return (QUESTION);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 129 "RegLex.l"
{
  return (PLUS);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 133 "RegLex.l"
{
  IncLevel ();
  return (OPENPAR);
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 138 "RegLex.l"
{
  DecLevel ();
  return (CLOSEPAR);
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 143 "RegLex.l"
{
  IncPosition ();
  SetPosition = 0;
  BEGIN SET;
  return (OPENNOSET);
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 150 "RegLex.l"
{
  IncPosition ();
  SetPosition = 0;
  BEGIN SET;
  return (OPENSET);
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 157 "RegLex.l"
{
  if (SetPosition == 0)
  {
    RegYYlval.character = RegYYtext[0];
    return (CHARACTER);
  }
  else
  {
    BEGIN EXP;
    return (CLOSESET);
  }
}
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 170 "RegLex.l"
{
  static RegCharRangeRec range;

  SetPosition++;

  range.c1 = RegYYtext[0];
  range.c2 = RegYYtext[2];
  RegYYlval.charRange = &range;
  return (CHARRANGE);
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 181 "RegLex.l"
{
  SetPosition++;
  RegYYlval.character = '\t';
  return (CHARACTER);
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 187 "RegLex.l"
{
  SetPosition++;
  RegYYlval.character = RegYYtext[0];
  return (CHARACTER);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 193 "RegLex.l"
{
  ResetPosition ();
  return (VERTICAL);
}
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 198 "RegLex.l"
{
  IncPosition ();
/*
  return (NEWLINE);
*/
  return (0);
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 206 "RegLex.l"
{
  IncPosition ();
  return (DOT);
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 211 "RegLex.l"
{
  if (!Position)
  {
    IncPosition ();
    return (CARRET);
  }
  else
  {
    IncPosition ();
    RegYYlval.character = RegYYtext[0];
    return (CHARACTER);
  }
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 225 "RegLex.l"
{
  IncPosition ();
  return (DOLLAR);
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 230 "RegLex.l"
{
  IncPosition ();
  RegYYlval.character = RegYYtext[0];
  return (CHARACTER);
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 236 "RegLex.l"
ECHO;
	YY_BREAK
#line 1075 "lex.RegYY.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(EXP):
case YY_STATE_EOF(SET):
	RegYYterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int RegYY_amount_of_matched_text = (int) (RegYY_cp - (RegYYtext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*RegYY_cp = (RegYY_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->RegYY_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed RegYYin at a new source and called
			 * RegYYlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(RegYY_n_chars) = YY_CURRENT_BUFFER_LVALUE->RegYY_n_chars;
			YY_CURRENT_BUFFER_LVALUE->RegYY_input_file = RegYYin;
			YY_CURRENT_BUFFER_LVALUE->RegYY_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for RegYY_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since RegYY_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (RegYY_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->RegYY_ch_buf[(RegYY_n_chars)] )
			{ /* This was really a NUL. */
			RegYY_state_type RegYY_next_state;

			(RegYY_c_buf_p) = (RegYYtext_ptr) + RegYY_amount_of_matched_text;

			RegYY_current_state = RegYY_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * RegYY_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			RegYY_next_state = RegYY_try_NUL_trans( RegYY_current_state );

			RegYY_bp = (RegYYtext_ptr) + YY_MORE_ADJ;

			if ( RegYY_next_state )
				{
				/* Consume the NUL. */
				RegYY_cp = ++(RegYY_c_buf_p);
				RegYY_current_state = RegYY_next_state;
				goto RegYY_match;
				}

			else
				{
				RegYY_cp = (RegYY_c_buf_p);
				goto RegYY_find_action;
				}
			}

		else switch ( RegYY_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(RegYY_did_buffer_switch_on_eof) = 0;

				if ( RegYYwrap( ) )
					{
					/* Note: because we've taken care in
					 * RegYY_get_next_buffer() to have set up
					 * RegYYtext, we can now set up
					 * RegYY_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(RegYY_c_buf_p) = (RegYYtext_ptr) + YY_MORE_ADJ;

					RegYY_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (RegYY_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(RegYY_c_buf_p) =
					(RegYYtext_ptr) + RegYY_amount_of_matched_text;

				RegYY_current_state = RegYY_get_previous_state(  );

				RegYY_cp = (RegYY_c_buf_p);
				RegYY_bp = (RegYYtext_ptr) + YY_MORE_ADJ;
				goto RegYY_match;

			case EOB_ACT_LAST_MATCH:
				(RegYY_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->RegYY_ch_buf[(RegYY_n_chars)];

				RegYY_current_state = RegYY_get_previous_state(  );

				RegYY_cp = (RegYY_c_buf_p);
				RegYY_bp = (RegYYtext_ptr) + YY_MORE_ADJ;
				goto RegYY_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of RegYYlex */

/* RegYY_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int RegYY_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->RegYY_ch_buf;
	register char *source = (RegYYtext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (RegYY_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->RegYY_ch_buf[(RegYY_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->RegYY_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (RegYY_c_buf_p) - (RegYYtext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((RegYY_c_buf_p) - (RegYYtext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->RegYY_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->RegYY_n_chars = (RegYY_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->RegYY_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int RegYY_c_buf_p_offset =
				(int) ((RegYY_c_buf_p) - b->RegYY_ch_buf);

			if ( b->RegYY_is_our_buffer )
				{
				int new_size = b->RegYY_buf_size * 2;

				if ( new_size <= 0 )
					b->RegYY_buf_size += b->RegYY_buf_size / 8;
				else
					b->RegYY_buf_size *= 2;

				b->RegYY_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					RegYYrealloc((void *) b->RegYY_ch_buf,b->RegYY_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->RegYY_ch_buf = 0;

			if ( ! b->RegYY_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(RegYY_c_buf_p) = &b->RegYY_ch_buf[RegYY_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->RegYY_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->RegYY_ch_buf[number_to_move]),
			(RegYY_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->RegYY_n_chars = (RegYY_n_chars);
		}

	if ( (RegYY_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			RegYYrestart(RegYYin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->RegYY_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((RegYY_size_t) ((RegYY_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->RegYY_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		RegYY_size_t new_size = (RegYY_n_chars) + number_to_move + ((RegYY_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->RegYY_ch_buf = (char *) RegYYrealloc((void *) YY_CURRENT_BUFFER_LVALUE->RegYY_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->RegYY_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in RegYY_get_next_buffer()" );
	}

	(RegYY_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->RegYY_ch_buf[(RegYY_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->RegYY_ch_buf[(RegYY_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(RegYYtext_ptr) = &YY_CURRENT_BUFFER_LVALUE->RegYY_ch_buf[0];

	return ret_val;
}

/* RegYY_get_previous_state - get the state just before the EOB char was reached */

    static RegYY_state_type RegYY_get_previous_state (void)
{
	register RegYY_state_type RegYY_current_state;
	register char *RegYY_cp;
    
	RegYY_current_state = (RegYY_start);

	for ( RegYY_cp = (RegYYtext_ptr) + YY_MORE_ADJ; RegYY_cp < (RegYY_c_buf_p); ++RegYY_cp )
		{
		register YY_CHAR RegYY_c = (*RegYY_cp ? RegYY_ec[YY_SC_TO_UI(*RegYY_cp)] : 1);
		if ( RegYY_accept[RegYY_current_state] )
			{
			(RegYY_last_accepting_state) = RegYY_current_state;
			(RegYY_last_accepting_cpos) = RegYY_cp;
			}
		while ( RegYY_chk[RegYY_base[RegYY_current_state] + RegYY_c] != RegYY_current_state )
			{
			RegYY_current_state = (int) RegYY_def[RegYY_current_state];
			if ( RegYY_current_state >= 46 )
				RegYY_c = RegYY_meta[(unsigned int) RegYY_c];
			}
		RegYY_current_state = RegYY_nxt[RegYY_base[RegYY_current_state] + (unsigned int) RegYY_c];
		}

	return RegYY_current_state;
}

/* RegYY_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = RegYY_try_NUL_trans( current_state );
 */
    static RegYY_state_type RegYY_try_NUL_trans  (RegYY_state_type RegYY_current_state )
{
	register int RegYY_is_jam;
    	register char *RegYY_cp = (RegYY_c_buf_p);

	register YY_CHAR RegYY_c = 1;
	if ( RegYY_accept[RegYY_current_state] )
		{
		(RegYY_last_accepting_state) = RegYY_current_state;
		(RegYY_last_accepting_cpos) = RegYY_cp;
		}
	while ( RegYY_chk[RegYY_base[RegYY_current_state] + RegYY_c] != RegYY_current_state )
		{
		RegYY_current_state = (int) RegYY_def[RegYY_current_state];
		if ( RegYY_current_state >= 46 )
			RegYY_c = RegYY_meta[(unsigned int) RegYY_c];
		}
	RegYY_current_state = RegYY_nxt[RegYY_base[RegYY_current_state] + (unsigned int) RegYY_c];
	RegYY_is_jam = (RegYY_current_state == 45);

	return RegYY_is_jam ? 0 : RegYY_current_state;
}

    static void RegYYunput (int c, register char * RegYY_bp )
{
	register char *RegYY_cp;
    
    RegYY_cp = (RegYY_c_buf_p);

	/* undo effects of setting up RegYYtext */
	*RegYY_cp = (RegYY_hold_char);

	if ( RegYY_cp < YY_CURRENT_BUFFER_LVALUE->RegYY_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (RegYY_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->RegYY_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->RegYY_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->RegYY_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->RegYY_ch_buf )
			*--dest = *--source;

		RegYY_cp += (int) (dest - source);
		RegYY_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->RegYY_n_chars =
			(RegYY_n_chars) = YY_CURRENT_BUFFER_LVALUE->RegYY_buf_size;

		if ( RegYY_cp < YY_CURRENT_BUFFER_LVALUE->RegYY_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--RegYY_cp = (char) c;

	(RegYYtext_ptr) = RegYY_bp;
	(RegYY_hold_char) = *RegYY_cp;
	(RegYY_c_buf_p) = RegYY_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int RegYYinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(RegYY_c_buf_p) = (RegYY_hold_char);

	if ( *(RegYY_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* RegYY_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (RegYY_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->RegYY_ch_buf[(RegYY_n_chars)] )
			/* This was really a NUL. */
			*(RegYY_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (RegYY_c_buf_p) - (RegYYtext_ptr);
			++(RegYY_c_buf_p);

			switch ( RegYY_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because RegYY_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					RegYYrestart(RegYYin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( RegYYwrap( ) )
						return EOF;

					if ( ! (RegYY_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return RegYYinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(RegYY_c_buf_p) = (RegYYtext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (RegYY_c_buf_p);	/* cast for 8-bit char's */
	*(RegYY_c_buf_p) = '\0';	/* preserve RegYYtext */
	(RegYY_hold_char) = *++(RegYY_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void RegYYrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        RegYYensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            RegYY_create_buffer(RegYYin,YY_BUF_SIZE );
	}

	RegYY_init_buffer(YY_CURRENT_BUFFER,input_file );
	RegYY_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void RegYY_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		RegYYpop_buffer_state();
	 *		RegYYpush_buffer_state(new_buffer);
     */
	RegYYensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(RegYY_c_buf_p) = (RegYY_hold_char);
		YY_CURRENT_BUFFER_LVALUE->RegYY_buf_pos = (RegYY_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->RegYY_n_chars = (RegYY_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	RegYY_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (RegYYwrap()) processing, but the only time this flag
	 * is looked at is after RegYYwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(RegYY_did_buffer_switch_on_eof) = 1;
}

static void RegYY_load_buffer_state  (void)
{
    	(RegYY_n_chars) = YY_CURRENT_BUFFER_LVALUE->RegYY_n_chars;
	(RegYYtext_ptr) = (RegYY_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->RegYY_buf_pos;
	RegYYin = YY_CURRENT_BUFFER_LVALUE->RegYY_input_file;
	(RegYY_hold_char) = *(RegYY_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE RegYY_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) RegYYalloc(sizeof( struct RegYY_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in RegYY_create_buffer()" );

	b->RegYY_buf_size = size;

	/* RegYY_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->RegYY_ch_buf = (char *) RegYYalloc(b->RegYY_buf_size + 2  );
	if ( ! b->RegYY_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in RegYY_create_buffer()" );

	b->RegYY_is_our_buffer = 1;

	RegYY_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with RegYY_create_buffer()
 * 
 */
    void RegYY_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->RegYY_is_our_buffer )
		RegYYfree((void *) b->RegYY_ch_buf  );

	RegYYfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a RegYYrestart() or at EOF.
 */
    static void RegYY_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	RegYY_flush_buffer(b );

	b->RegYY_input_file = file;
	b->RegYY_fill_buffer = 1;

    /* If b is the current buffer, then RegYY_init_buffer was _probably_
     * called from RegYYrestart() or through RegYY_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->RegYY_bs_lineno = 1;
        b->RegYY_bs_column = 0;
    }

        b->RegYY_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void RegYY_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->RegYY_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->RegYY_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->RegYY_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->RegYY_buf_pos = &b->RegYY_ch_buf[0];

	b->RegYY_at_bol = 1;
	b->RegYY_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		RegYY_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void RegYYpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	RegYYensure_buffer_stack();

	/* This block is copied from RegYY_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(RegYY_c_buf_p) = (RegYY_hold_char);
		YY_CURRENT_BUFFER_LVALUE->RegYY_buf_pos = (RegYY_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->RegYY_n_chars = (RegYY_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(RegYY_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from RegYY_switch_to_buffer. */
	RegYY_load_buffer_state( );
	(RegYY_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void RegYYpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	RegYY_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((RegYY_buffer_stack_top) > 0)
		--(RegYY_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		RegYY_load_buffer_state( );
		(RegYY_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void RegYYensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(RegYY_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(RegYY_buffer_stack) = (struct RegYY_buffer_state**)RegYYalloc
								(num_to_alloc * sizeof(struct RegYY_buffer_state*)
								);
		if ( ! (RegYY_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in RegYYensure_buffer_stack()" );
								  
		memset((RegYY_buffer_stack), 0, num_to_alloc * sizeof(struct RegYY_buffer_state*));
				
		(RegYY_buffer_stack_max) = num_to_alloc;
		(RegYY_buffer_stack_top) = 0;
		return;
	}

	if ((RegYY_buffer_stack_top) >= ((RegYY_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (RegYY_buffer_stack_max) + grow_size;
		(RegYY_buffer_stack) = (struct RegYY_buffer_state**)RegYYrealloc
								((RegYY_buffer_stack),
								num_to_alloc * sizeof(struct RegYY_buffer_state*)
								);
		if ( ! (RegYY_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in RegYYensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((RegYY_buffer_stack) + (RegYY_buffer_stack_max), 0, grow_size * sizeof(struct RegYY_buffer_state*));
		(RegYY_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE RegYY_scan_buffer  (char * base, RegYY_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) RegYYalloc(sizeof( struct RegYY_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in RegYY_scan_buffer()" );

	b->RegYY_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->RegYY_buf_pos = b->RegYY_ch_buf = base;
	b->RegYY_is_our_buffer = 0;
	b->RegYY_input_file = 0;
	b->RegYY_n_chars = b->RegYY_buf_size;
	b->RegYY_is_interactive = 0;
	b->RegYY_at_bol = 1;
	b->RegYY_fill_buffer = 0;
	b->RegYY_buffer_status = YY_BUFFER_NEW;

	RegYY_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to RegYYlex() will
 * scan from a @e copy of @a str.
 * @param RegYYstr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       RegYY_scan_bytes() instead.
 */
YY_BUFFER_STATE RegYY_scan_string (RegYYconst char * RegYYstr )
{
    
	return RegYY_scan_bytes(RegYYstr,strlen(RegYYstr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to RegYYlex() will
 * scan from a @e copy of @a bytes.
 * @param RegYYbytes the byte buffer to scan
 * @param _RegYYbytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE RegYY_scan_bytes  (RegYYconst char * RegYYbytes, int  _RegYYbytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	RegYY_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _RegYYbytes_len + 2;
	buf = (char *) RegYYalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in RegYY_scan_bytes()" );

	for ( i = 0; i < _RegYYbytes_len; ++i )
		buf[i] = RegYYbytes[i];

	buf[_RegYYbytes_len] = buf[_RegYYbytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = RegYY_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in RegYY_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->RegYY_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void RegYY_fatal_error (RegYYconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine RegYYless() so it works in section 3 code. */

#undef RegYYless
#define RegYYless(n) \
	do \
		{ \
		/* Undo effects of setting up RegYYtext. */ \
        int RegYYless_macro_arg = (n); \
        YY_LESS_LINENO(RegYYless_macro_arg);\
		RegYYtext[RegYYleng] = (RegYY_hold_char); \
		(RegYY_c_buf_p) = RegYYtext + RegYYless_macro_arg; \
		(RegYY_hold_char) = *(RegYY_c_buf_p); \
		*(RegYY_c_buf_p) = '\0'; \
		RegYYleng = RegYYless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int RegYYget_lineno  (void)
{
        
    return RegYYlineno;
}

/** Get the input stream.
 * 
 */
FILE *RegYYget_in  (void)
{
        return RegYYin;
}

/** Get the output stream.
 * 
 */
FILE *RegYYget_out  (void)
{
        return RegYYout;
}

/** Get the length of the current token.
 * 
 */
int RegYYget_leng  (void)
{
        return RegYYleng;
}

/** Get the current token.
 * 
 */

char *RegYYget_text  (void)
{
        return RegYYtext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void RegYYset_lineno (int  line_number )
{
    
    RegYYlineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see RegYY_switch_to_buffer
 */
void RegYYset_in (FILE *  in_str )
{
        RegYYin = in_str ;
}

void RegYYset_out (FILE *  out_str )
{
        RegYYout = out_str ;
}

int RegYYget_debug  (void)
{
        return RegYY_flex_debug;
}

void RegYYset_debug (int  bdebug )
{
        RegYY_flex_debug = bdebug ;
}

static int RegYY_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from RegYYlex_destroy(), so don't allocate here.
     */

    (RegYY_buffer_stack) = 0;
    (RegYY_buffer_stack_top) = 0;
    (RegYY_buffer_stack_max) = 0;
    (RegYY_c_buf_p) = (char *) 0;
    (RegYY_init) = 0;
    (RegYY_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    RegYYin = stdin;
    RegYYout = stdout;
#else
    RegYYin = (FILE *) 0;
    RegYYout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * RegYYlex_init()
     */
    return 0;
}

/* RegYYlex_destroy is for both reentrant and non-reentrant scanners. */
int RegYYlex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		RegYY_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		RegYYpop_buffer_state();
	}

	/* Destroy the stack itself. */
	RegYYfree((RegYY_buffer_stack) );
	(RegYY_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * RegYYlex() is called, initialization will occur. */
    RegYY_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef RegYYtext_ptr
static void RegYY_flex_strncpy (char* s1, RegYYconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int RegYY_flex_strlen (RegYYconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *RegYYalloc (RegYY_size_t  size )
{
	return (void *) malloc( size );
}

void *RegYYrealloc  (void * ptr, RegYY_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void RegYYfree (void * ptr )
{
	free( (char *) ptr );	/* see RegYYrealloc() for (char *) cast */
}

#define YYTABLES_NAME "RegYYtables"

#line 236 "RegLex.l"



void IncLevel ()
{
  if (Level == Levels)
  {
    Levels += 10;
    if (Positions)
    {
      Positions = (int*) realloc (Positions, Levels*sizeof(int));
    }
    else
    {
      Positions = (int*) malloc (Levels*sizeof(int));
    }
  }

  Level++;
  Positions[Level-1] = Position;
}

void DecLevel ()
{
  if (Level > 0) Level--;
}

void IncPosition ()
{
  if (!Level) IncLevel ();

  Position++;
}

void ResetPosition ()
{
  if (!Level) IncLevel ();

  Position = Positions[Level-1];
}

void RegLexStartup (char* text)
{
  RegYYin = stdin;
  RegYYout = stdout;

  BEGIN EXP;
  Level = 0;
  Position = 0;
  CurrentText = text;
  CurrentPos = 0;
}

int RegLexInput ()
{
  char c;

  c = CurrentText[CurrentPos];
  CurrentPos++;

  return (c);
}

static void RegLexUnput (int c)
{
  CurrentPos--;
  CurrentText[CurrentPos] = c;
}


